# version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: Log-Aggregation-Analytics-DB
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: log_analytics-db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/log_analytics-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build: ./frontend
    # For development, we can mount the source code and node_modules to enable hot reloading
    volumes:
      - ./frontend:/app
      - /app/node_modules # This prevents Docker from overwriting your packages
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data: